(add-to-list 'load-path "~/.emacs.d.custom/user-lisp")
(add-to-list 'load-path "./ohther-packages")
(require 'init-evil)
(require 'init-blog)
(require 'init-userOrg)
(require 'init-userWindow)
(require 'init-builtin)
(require 'init-lazyCat)
(require 'init-async)
(require 'init-helm)
(require 'init-dev)
