(add-to-list 'load-path "~/.emacs.d.custom/user-lisp")
(add-to-list 'load-path "./ohther-packages")
;;(require 'init-awesomeTab)
(require 'init-evil)
(require 'init-blog)
(require 'init-userOrg)
;; (require 'init-csharp)
(require 'init-userWindow)
;; (require 'init-snails)
(require 'init-builtin)
(require 'init-lazyCat)
(require 'init-dap)
